import Head from "next/head"
import Sidebar from "@/components/Sidebar"
import MainComp from "@/components/MainComp"
export default function Home() {
  return (
    <>
      <Head>
        <title>Truffles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex bg-gray-100">
    <Sidebar />
    <MainComp />
    </div>
    </>
  )
}
